# Naive data tpot

In [8]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import copy
from Modules import *
sns.set()
%matplotlib inline
import tpot
import imblearn

In [3]:
df = pd.read_csv('Sequential_Data1.csv')
y = df['Y']

df.head().T

,0,1,2,3,4
LIMIT_BAL,20000.000000,120000.000000,90000.000000,50000.000000,50000.000000
AGE,24.000000,26.000000,34.000000,37.000000,57.000000
PAY_1,2.000000,-1.000000,0.000000,0.000000,-1.000000
PAY_2,2.000000,2.000000,0.000000,0.000000,0.000000
PAY_3,-1.000000,0.000000,0.000000,0.000000,-1.000000
PAY_4,-1.000000,0.000000,0.000000,0.000000,0.000000
PAY_5,-2.000000,0.000000,0.000000,0.000000,0.000000
PAY_6,-2.000000,2.000000,0.000000,0.000000,0.000000
BILL_AMT1,3913.000000,2682.000000,29239.000000,46990.000000,8617.000000
BILL_AMT2,3102.000000,1725.000000,14027.000000,48233.000000,5670.000000
BILL_AMT3,689.000000,2682.000000,13559.000000,49291.000000,35835.000000
BILL_AMT4,0.000000,3272.000000,14331.000000,28314.000000,20940.000000
BILL_AMT5,0.000000,3455.000000,14948.000000,28959.000000,19146.000000
BILL_AMT6,0.000000,3261.000000,15549.000000,29547.000000,19131.000000
PAY_AMT1,0.000000,0.000000,1518.000000,2000.000000,2000.000000
PAY_AMT2,689.000000,1000.000000,1500.000000,2019.000000,36681.000000
PAY_AMT3,0.000000,1000.000000,1000.000000,1200.000000,10000.000000
PAY_AMT4,0.000000,1000.000000,1000.000000,1100.000000,9000.000000
PAY_AMT5,0.000000,0.000000,1000.000000,1069.000000,689.000000
PAY_AMT6,0.000000,2000.000000,5000.000000,1000.000000,679.000000
Y,1.000000,1.000000,0.000000,0.000000,0.000000
SEX_Female,1.000000,1.000000,1.000000,1.000000,0.000000
SEX_Male,0.000000,0.000000,0.000000,0.000000,1.000000
EDUCATION_Graduate School,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_Other,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_University,1.000000,1.000000,1.000000,1.000000,1.000000
MARRIAGE_Married,1.000000,0.000000,0.000000,1.000000,1.000000
MARRIAGE_Non-married,0.000000,1.000000,1.000000,0.000000,0.000000
OUTSTANDING_BAL1,3913.000000,2682.000000,27721.000000,44990.000000,6617.000000
OUTSTANDING_BAL2,2413.000000,725.000000,12527.000000,46214.000000,-31011.000000
...,...,...,...,...,...
OUTSTANDING_BAL4,0.000000,2272.000000,13331.000000,27214.000000,11940.000000
OUTSTANDING_BAL5,0.000000,3455.000000,13948.000000,27890.000000,18457.000000
OUTSTANDING_BAL6,0.000000,1261.000000,10549.000000,28547.000000,18452.000000
OUSTANDING_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
OUSTANDING_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
OUSTANDING_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
OUSTANDING_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
OUSTANDING_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL1,0.195650,0.022350,0.308011,0.899800,0.132340
PERCENT_OF_LIMIT_BAL2,0.120650,0.006042,0.139189,0.924280,-0.620220
PERCENT_OF_LIMIT_BAL3,0.034450,0.014017,0.139544,0.961820,0.516700
PERCENT_OF_LIMIT_BAL4,0.000000,0.018933,0.148122,0.544280,0.238800
PERCENT_OF_LIMIT_BAL5,0.000000,0.028792,0.154978,0.557800,0.369140
PERCENT_OF_LIMIT_BAL6,0.000000,0.010508,0.117211,0.570940,0.369040
PERCENT_OF_LIMIT_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
PERCENT_OF_LIMIT_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_1,0.000000,0.000000,0.051917,0.042562,0.232099
PAY_RATIO_2,0.222115,0.579710,0.106937,0.041859,6.469312
PAY_RATIO_3,0.000000,0.372856,0.073752,0.024345,0.279057
PAY_RATIO_4,1.000000,0.305623,0.069779,0.038850,0.429799
PAY_RATIO_5,1.000000,0.000000,0.066899,0.036914,0.035987
PAY_RATIO_6,1.000000,0.613309,0.321564,0.033844,0.035492
PAY_RATIO_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_2_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_3_INDICATOR,0.600000,0.000000,0.000000,0.600000,0.600000
PAY_RATIO_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_5_INDICATOR,0.000000,0.200000,0.200000,0.000000,0.000000

In [4]:
df.columns

Index(['LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'Y', 'SEX_Female', 'SEX_Male',
       'EDUCATION_Graduate School', 'EDUCATION_Other', 'EDUCATION_University',
       'MARRIAGE_Married', 'MARRIAGE_Non-married', 'OUTSTANDING_BAL1',
       'OUTSTANDING_BAL2', 'OUTSTANDING_BAL3', 'OUTSTANDING_BAL4',
       'OUTSTANDING_BAL5', 'OUTSTANDING_BAL6', 'OUSTANDING_BAL_1_INDICATOR',
       'OUSTANDING_BAL_2_INDICATOR', 'OUSTANDING_BAL_3_INDICATOR',
       'OUSTANDING_BAL_4_INDICATOR', 'OUSTANDING_BAL_5_INDICATOR',
       'PERCENT_OF_LIMIT_BAL1', 'PERCENT_OF_LIMIT_BAL2',
       'PERCENT_OF_LIMIT_BAL3', 'PERCENT_OF_LIMIT_BAL4',
       'PERCENT_OF_LIMIT_BAL5', 'PERCENT_OF_LIMIT_BAL6',
       'PERCENT_OF_LIMIT_BAL_1_INDICATOR', 'PERCENT_OF_LIMIT_BAL_2_INDICATOR',
       'PERCENT_OF_LIMIT_BAL_3_INDICATOR', 'PERCENT_OF_LIMIT_BAL_4_INDICATOR',
       'PERCENT_OF_LIMIT_BAL_5_INDICATOR', 'PAY_RATIO_1', 'PAY_RATIO_2',
       'PAY_RATIO_3', 'PAY_RATIO_4', 'PAY_RATIO_5', 'PAY_RATIO_6',
       'PAY_RATIO_1_INDICATOR', 'PAY_RATIO_2_INDICATOR',
       'PAY_RATIO_3_INDICATOR', 'PAY_RATIO_4_INDICATOR',
       'PAY_RATIO_5_INDICATOR'],
      dtype='object')

In the naive notebook, we didn't trim any of the intermediate features, in that there are still features whose values are used to create new features, which would inherently make all of these features too highly correlated with each other. So here, we will eliminate feautes used in calculation of the new feautures, which includes the pay_amt, bill_amt, and the outstanding balances.

In [ ]:
#trim down intermediate variables. 

trim_columns = ['LIMIT_BAL','BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6','OUTSTANDING_BAL1',
       'OUTSTANDING_BAL2', 'OUTSTANDING_BAL3', 'OUTSTANDING_BAL4',
       'OUTSTANDING_BAL5', 'OUTSTANDING_BAL6', 'OUSTANDING_BAL_1_INDICATOR',
       'OUSTANDING_BAL_2_INDICATOR', 'OUSTANDING_BAL_3_INDICATOR',
       'OUSTANDING_BAL_4_INDICATOR', 'OUSTANDING_BAL_5_INDICATOR']

df = df.drop(columns = trim_columns)

In [6]:
df.head().T

,0,1,2,3,4
AGE,24.000000,26.000000,34.000000,37.000000,57.000000
PAY_1,2.000000,-1.000000,0.000000,0.000000,-1.000000
PAY_2,2.000000,2.000000,0.000000,0.000000,0.000000
PAY_3,-1.000000,0.000000,0.000000,0.000000,-1.000000
PAY_4,-1.000000,0.000000,0.000000,0.000000,0.000000
PAY_5,-2.000000,0.000000,0.000000,0.000000,0.000000
PAY_6,-2.000000,2.000000,0.000000,0.000000,0.000000
Y,1.000000,1.000000,0.000000,0.000000,0.000000
SEX_Female,1.000000,1.000000,1.000000,1.000000,0.000000
SEX_Male,0.000000,0.000000,0.000000,0.000000,1.000000
EDUCATION_Graduate School,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_Other,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_University,1.000000,1.000000,1.000000,1.000000,1.000000
MARRIAGE_Married,1.000000,0.000000,0.000000,1.000000,1.000000
MARRIAGE_Non-married,0.000000,1.000000,1.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL1,0.195650,0.022350,0.308011,0.899800,0.132340
PERCENT_OF_LIMIT_BAL2,0.120650,0.006042,0.139189,0.924280,-0.620220
PERCENT_OF_LIMIT_BAL3,0.034450,0.014017,0.139544,0.961820,0.516700
PERCENT_OF_LIMIT_BAL4,0.000000,0.018933,0.148122,0.544280,0.238800
PERCENT_OF_LIMIT_BAL5,0.000000,0.028792,0.154978,0.557800,0.369140
PERCENT_OF_LIMIT_BAL6,0.000000,0.010508,0.117211,0.570940,0.369040
PERCENT_OF_LIMIT_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
PERCENT_OF_LIMIT_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_1,0.000000,0.000000,0.051917,0.042562,0.232099
PAY_RATIO_2,0.222115,0.579710,0.106937,0.041859,6.469312
PAY_RATIO_3,0.000000,0.372856,0.073752,0.024345,0.279057
PAY_RATIO_4,1.000000,0.305623,0.069779,0.038850,0.429799
PAY_RATIO_5,1.000000,0.000000,0.066899,0.036914,0.035987
PAY_RATIO_6,1.000000,0.613309,0.321564,0.033844,0.035492
PAY_RATIO_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_2_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_3_INDICATOR,0.600000,0.000000,0.000000,0.600000,0.600000
PAY_RATIO_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_5_INDICATOR,0.000000,0.200000,0.200000,0.000000,0.000000

In [12]:
#evaluate using the baseline evaluator.

def evaluate_baseline_new(df, NB = True):
    '''evalueates a df with a Guassian Naive Bayes Model.
        Input: a dataframe
               NB = True is want to run a simple Naive Bayes model
               NB= False if want to run a simple Logistic Regression Model
        Output: 10-fold cross validation f1 score and AUC score.
    
    '''
    import pandas as pd
    import numpy as np
    from sklearn.naive_bayes import GaussianNB
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split
    from sklearn.naive_bayes import GaussianNB
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split, KFold, cross_val_score
    from sklearn.metrics import classification_report, confusion_matrix
    from imblearn.pipeline import make_pipeline, Pipeline
    from imblearn.over_sampling import RandomOverSampler

    X = df.drop('Y', axis = 1)
    y = df['Y']

    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2019)

    #begin oversampling pipeline
    if NB:
        clf = GaussianNB()
    else:
        clf = LogisticRegression()
    
    oversampler = RandomOverSampler(random_state = 2019)
    pipeline = make_pipeline(oversampler, clf)
    
    pipeline.fit(X_train, y_train)
    
    #10-fold cross validation
    kfold = KFold(n_splits=10, random_state=2019)
    results = cross_val_score(pipeline, X_test, y_test, cv=kfold, scoring='f1')
    print(results)
    print()
    print('corss-validation f1 score:', np.mean(results))

In [13]:
evaluate_baseline_new(df)

[0.41925466 0.34678625 0.3440367  0.43465909 0.3837535  0.43313953
 0.38132296 0.4024024  0.39888424 0.35450517]

corss-validation f1 score: 0.3898744500314042

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = 'Y')


X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2019, train_size = .75)

C:\Users\kevin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [6]:
X_train.shape

(22500, 60)

In [7]:
from tpot import TPOTClassifier

tpot = TPOTClassifier(verbosity = 2, max_time_mins=360, scoring = 'f1', random_state = 2019)

tpot.fit(X.values, y.values)

C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

HBox(children=(IntProgress(value=0, description='Optimization Progress', style=ProgressStyle(description_width…

Generation 1 - Current best internal CV score: 0.49510757579372305

360.3392754166667 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: BernoulliNB(DecisionTreeClassifier(input_matrix, criterion=gini, max_depth=5, min_samples_leaf=2, min_samples_split=6), alpha=100.0, fit_prior=False)

TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
        disable_update_check=False, early_stop=None, generations=1000000,
        max_eval_time_mins=5, max_time_mins=360, memory=None,
        mutation_rate=0.9, n_jobs=1, offspring_size=None,
        periodic_checkpoint_folder=None, population_size=100,
        random_state=2019, scoring='f1', subsample=1.0,
        template='RandomTree', use_dask=False, verbosity=2,
        warm_start=False)

In [11]:
tpot.score(X_test.values, y_test.values)

0.5173867228661749

In [9]:
tpot.export('Sequential_TPOT_best2.py')

## hyperparamters for two datasets:

- generations: Number of iterations to the run pipeline optimization process. The default is 100.
- population_size: Number of individuals to retain in the genetic programming population every generation. The default is 100.
- offspring_size: Number of offspring to produce in each genetic programming generation. The default is 100.
- mutation_rate: Mutation rate for the genetic programming algorithm in the range [0.0, 1.0]. This parameter tells the GP algorithm how many pipelines to apply random changes to every generation. Default is 0.9
- crossover_rate: Crossover rate for the genetic programming algorithm in the range [0.0, 1.0]. This parameter tells the genetic programming algorithm how many pipelines to "breed" every generation.
- scoring: Function used to evaluate the quality of a given pipeline for the classification problem like accuracy, average_precision, roc_auc, recall, etc. The default is accuracy.
- cv: Cross-validation strategy used when evaluating pipelines. The default is 5.
- random_state: The seed of the pseudo-random number generator used in TPOT. Use this parameter to make sure that TPOT will give you the same results each time you run it against the same data set with that seed.

Of these to change: we will use scoring = 'f1', random_state = 2019. Verbosity = 2, Max_time_mins = 360, max_eval_time_mins = 6, All else is the default.

Good luck!

In [22]:
#my attempt to build a pipeline with SMOTE

from imblearn.pipeline import make_pipeline, Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import Binarizer, PolynomialFeatures
from sklearn.model_selection import KFold, cross_val_score

#read in the data, same as the TPOT pipeline
tpot_data = pd.read_csv('Sequential_Data1.csv', sep=',', dtype=np.float64)
features = tpot_data.drop('Y', axis=1).values
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['Y'].values, random_state=2019)

#instatiate pipeline sequences
#oversampling
smote = SMOTE(random_state = 2019, n_jobs=-1)

#steps from best tpot pipeline
poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
binarizer = Binarizer(threshold=0.8)
clf = BernoulliNB(alpha=10.0, fit_prior=True)

#build the pipeline
pipeline = make_pipeline(smote, poly, binarizer, clf)
pipeline.fit(training_features, training_target)

#set criteria for cross_validation scoring
kf = KFold(n_splits = 5, random_state = 2019)

#store the scores in an array
scores = cross_val_score(pipeline, X = testing_features,  y= testing_target, cv=kf, scoring = 'f1')

print(scores)
print(f"cross-validation f1 score: {np.mean(scores)}")

[0.47841727 0.52615845 0.47987118 0.51215559 0.47811448]
cross-validation f1 score: 0.4949433913675915