# Trimmed Sequential Data

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import copy
from Modules import *
sns.set()
%matplotlib inline
import tpot
import imblearn

C:\Users\kevin\Anaconda3\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap_external.py:426: ImportWarning: Not importing directory C:\Users\kevin\Anaconda3\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap_external.py:426: ImportWarning: Not importing directory c:\users\kevin\anaconda3\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

### read in the full sequential data

In [2]:
df = pd.read_csv('Sequential_Data1.csv')
y = df['Y']

df.head().T

,0,1,2,3,4
LIMIT_BAL,20000.000000,120000.000000,90000.000000,50000.000000,50000.000000
AGE,24.000000,26.000000,34.000000,37.000000,57.000000
PAY_1,2.000000,-1.000000,0.000000,0.000000,-1.000000
PAY_2,2.000000,2.000000,0.000000,0.000000,0.000000
PAY_3,-1.000000,0.000000,0.000000,0.000000,-1.000000
PAY_4,-1.000000,0.000000,0.000000,0.000000,0.000000
PAY_5,-2.000000,0.000000,0.000000,0.000000,0.000000
PAY_6,-2.000000,2.000000,0.000000,0.000000,0.000000
BILL_AMT1,3913.000000,2682.000000,29239.000000,46990.000000,8617.000000
BILL_AMT2,3102.000000,1725.000000,14027.000000,48233.000000,5670.000000
BILL_AMT3,689.000000,2682.000000,13559.000000,49291.000000,35835.000000
BILL_AMT4,0.000000,3272.000000,14331.000000,28314.000000,20940.000000
BILL_AMT5,0.000000,3455.000000,14948.000000,28959.000000,19146.000000
BILL_AMT6,0.000000,3261.000000,15549.000000,29547.000000,19131.000000
PAY_AMT1,0.000000,0.000000,1518.000000,2000.000000,2000.000000
PAY_AMT2,689.000000,1000.000000,1500.000000,2019.000000,36681.000000
PAY_AMT3,0.000000,1000.000000,1000.000000,1200.000000,10000.000000
PAY_AMT4,0.000000,1000.000000,1000.000000,1100.000000,9000.000000
PAY_AMT5,0.000000,0.000000,1000.000000,1069.000000,689.000000
PAY_AMT6,0.000000,2000.000000,5000.000000,1000.000000,679.000000
Y,1.000000,1.000000,0.000000,0.000000,0.000000
SEX_Female,1.000000,1.000000,1.000000,1.000000,0.000000
SEX_Male,0.000000,0.000000,0.000000,0.000000,1.000000
EDUCATION_Graduate School,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_Other,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_University,1.000000,1.000000,1.000000,1.000000,1.000000
MARRIAGE_Married,1.000000,0.000000,0.000000,1.000000,1.000000
MARRIAGE_Non-married,0.000000,1.000000,1.000000,0.000000,0.000000
OUTSTANDING_BAL1,3913.000000,2682.000000,27721.000000,44990.000000,6617.000000
OUTSTANDING_BAL2,2413.000000,725.000000,12527.000000,46214.000000,-31011.000000
...,...,...,...,...,...
OUTSTANDING_BAL4,0.000000,2272.000000,13331.000000,27214.000000,11940.000000
OUTSTANDING_BAL5,0.000000,3455.000000,13948.000000,27890.000000,18457.000000
OUTSTANDING_BAL6,0.000000,1261.000000,10549.000000,28547.000000,18452.000000
OUSTANDING_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
OUSTANDING_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
OUSTANDING_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
OUSTANDING_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
OUSTANDING_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL1,0.195650,0.022350,0.308011,0.899800,0.132340
PERCENT_OF_LIMIT_BAL2,0.120650,0.006042,0.139189,0.924280,-0.620220
PERCENT_OF_LIMIT_BAL3,0.034450,0.014017,0.139544,0.961820,0.516700
PERCENT_OF_LIMIT_BAL4,0.000000,0.018933,0.148122,0.544280,0.238800
PERCENT_OF_LIMIT_BAL5,0.000000,0.028792,0.154978,0.557800,0.369140
PERCENT_OF_LIMIT_BAL6,0.000000,0.010508,0.117211,0.570940,0.369040
PERCENT_OF_LIMIT_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
PERCENT_OF_LIMIT_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_1,0.000000,0.000000,0.051917,0.042562,0.232099
PAY_RATIO_2,0.222115,0.579710,0.106937,0.041859,6.469312
PAY_RATIO_3,0.000000,0.372856,0.073752,0.024345,0.279057
PAY_RATIO_4,1.000000,0.305623,0.069779,0.038850,0.429799
PAY_RATIO_5,1.000000,0.000000,0.066899,0.036914,0.035987
PAY_RATIO_6,1.000000,0.613309,0.321564,0.033844,0.035492
PAY_RATIO_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_2_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_3_INDICATOR,0.600000,0.000000,0.000000,0.600000,0.600000
PAY_RATIO_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_5_INDICATOR,0.000000,0.200000,0.200000,0.000000,0.000000

In the `Naive_TPOT-Copy1.ipynb`, we didn't trim any of the intermediate features, in that there are still features whose values are used to create new features, which would inherently make all of these features too highly correlated with each other. So here, we will eliminate feautes used in calculation of the new feautures, which includes the pay_amt, bill_amt, and the outstanding balances.

In [3]:
columns_drop = ['LIMIT_BAL', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'OUTSTANDING_BAL1',
       'OUTSTANDING_BAL2', 'OUTSTANDING_BAL3', 'OUTSTANDING_BAL4',
       'OUTSTANDING_BAL5', 'OUTSTANDING_BAL6', 'OUSTANDING_BAL_1_INDICATOR',
       'OUSTANDING_BAL_2_INDICATOR', 'OUSTANDING_BAL_3_INDICATOR',
       'OUSTANDING_BAL_4_INDICATOR', 'OUSTANDING_BAL_5_INDICATOR']

df_trimmed = df.drop(columns = columns_drop)

In [4]:
df_trimmed.head().T

,0,1,2,3,4
AGE,24.000000,26.000000,34.000000,37.000000,57.000000
PAY_1,2.000000,-1.000000,0.000000,0.000000,-1.000000
PAY_2,2.000000,2.000000,0.000000,0.000000,0.000000
PAY_3,-1.000000,0.000000,0.000000,0.000000,-1.000000
PAY_4,-1.000000,0.000000,0.000000,0.000000,0.000000
PAY_5,-2.000000,0.000000,0.000000,0.000000,0.000000
PAY_6,-2.000000,2.000000,0.000000,0.000000,0.000000
Y,1.000000,1.000000,0.000000,0.000000,0.000000
SEX_Female,1.000000,1.000000,1.000000,1.000000,0.000000
SEX_Male,0.000000,0.000000,0.000000,0.000000,1.000000
EDUCATION_Graduate School,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_Other,0.000000,0.000000,0.000000,0.000000,0.000000
EDUCATION_University,1.000000,1.000000,1.000000,1.000000,1.000000
MARRIAGE_Married,1.000000,0.000000,0.000000,1.000000,1.000000
MARRIAGE_Non-married,0.000000,1.000000,1.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL1,0.195650,0.022350,0.308011,0.899800,0.132340
PERCENT_OF_LIMIT_BAL2,0.120650,0.006042,0.139189,0.924280,-0.620220
PERCENT_OF_LIMIT_BAL3,0.034450,0.014017,0.139544,0.961820,0.516700
PERCENT_OF_LIMIT_BAL4,0.000000,0.018933,0.148122,0.544280,0.238800
PERCENT_OF_LIMIT_BAL5,0.000000,0.028792,0.154978,0.557800,0.369140
PERCENT_OF_LIMIT_BAL6,0.000000,0.010508,0.117211,0.570940,0.369040
PERCENT_OF_LIMIT_BAL_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PERCENT_OF_LIMIT_BAL_2_INDICATOR,1.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_3_INDICATOR,1.000000,0.000000,0.000000,1.000000,1.000000
PERCENT_OF_LIMIT_BAL_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PERCENT_OF_LIMIT_BAL_5_INDICATOR,0.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_1,0.000000,0.000000,0.051917,0.042562,0.232099
PAY_RATIO_2,0.222115,0.579710,0.106937,0.041859,6.469312
PAY_RATIO_3,0.000000,0.372856,0.073752,0.024345,0.279057
PAY_RATIO_4,1.000000,0.305623,0.069779,0.038850,0.429799
PAY_RATIO_5,1.000000,0.000000,0.066899,0.036914,0.035987
PAY_RATIO_6,1.000000,0.613309,0.321564,0.033844,0.035492
PAY_RATIO_1_INDICATOR,1.000000,1.000000,1.000000,0.000000,1.000000
PAY_RATIO_2_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_3_INDICATOR,0.600000,0.000000,0.000000,0.600000,0.600000
PAY_RATIO_4_INDICATOR,0.000000,0.000000,0.000000,0.000000,0.000000
PAY_RATIO_5_INDICATOR,0.000000,0.200000,0.200000,0.000000,0.000000

In [5]:
#df_trimmed.to_csv('Seqential_data_trimmed.csv', sep=',')

## Baseline evaluation

Using the baseline evaluation code in our `Modules.py` file

In [6]:
#evaluate using the baseline evaluator.
evaluate_baseline(df_trimmed, clf = 'Logistic')

10-fold f1 scores:
[0.43203883 0.4400978  0.45714286 0.49217002 0.46778043 0.47006652
 0.46511628 0.50717703 0.47906977 0.43349754]

corss-validation f1 score: 0.4644157079368223

## Evaluation of `Sequential_TPOT1.py` code

In [9]:
#build a pipeline with SMOTE and Sequential_TPOT1.py

from imblearn.pipeline import make_pipeline, Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import Binarizer, PolynomialFeatures
from sklearn.model_selection import KFold, cross_val_score, train_test_split

#read in the data, same as the TPOT pipeline
tpot_data = pd.read_csv('Sequential_data_trimmed.csv', sep=',', dtype=np.float64)
features = tpot_data.drop('Y', axis=1).values
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['Y'].values, random_state=2019)

#instatiate pipeline sequences
#oversampling
smote = SMOTE(random_state = 2019, n_jobs=-1)

#steps from best tpot pipeline
poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
binarizer = Binarizer(threshold=0.8)
clf = BernoulliNB(alpha=10.0, fit_prior=True)

#build the pipeline
pipeline = make_pipeline(smote, poly, binarizer, clf)
pipeline.fit(training_features, training_target)

#set criteria for cross_validation scoring
kf = KFold(n_splits = 10, random_state = 2019)

#store the scores in an array
scores = cross_val_score(pipeline, X = testing_features,  y= testing_target, cv=kf, scoring = 'f1')

print(scores)
print(f"cross-validation f1 score: {np.mean(scores)}")

[0.48979592 0.47651007 0.53687316 0.54237288 0.46905537 0.5129683
 0.49101796 0.54019293 0.4952381  0.5       ]
cross-validation f1 score: 0.5054024682839173

## Evaluation of basic XGBoost classifier

In [5]:
XGBoost_evaluate(df_trimmed)

10-fold f1 scores:
[0.42931937 0.48387097 0.44186047 0.45918367 0.49302326 0.39572193
 0.42592593 0.51515152 0.48430493 0.51648352]

corss-validation f1 score: 0.4644845549299378

## Create another TPOT run, using only XGBoost and RandomForests, ExtraTrees, GradientBoostingClassifier.

In [ ]:
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

X = df.drop(columns = ['Y'])
y = df['Y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2019)

oversampler = SMOTE(random_state = 2019)
X_train_oversampled, y_train_oversampled = oversampler.fit_resample(X_train, y_train)

X_train_oversampled = pd.DataFrame(X_train_oversampled, columns = X_train.columns)
y_train_oversampled = pd.Series(y_train_oversampled)

#run tpot
tpot = TPOTClassifier(verbosity=2, n_jobs = -1, scoring = 'f1', random_state = 2019)
tpot.fit(X_train_oversampled, y_train_oversampled)
print(tpot.score(X_test, y_test))
tpot.export('tpot_sequential_data_trimmed.py')

C:\Users\kevin\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

HBox(children=(IntProgress(value=0, description='Optimization Progress', max=10100, style=ProgressStyle(descri…

Generation 1 - Current best internal CV score: 0.8341928231513014
Generation 2 - Current best internal CV score: 0.8341928231513014
Generation 3 - Current best internal CV score: 0.8345135476152284
Generation 4 - Current best internal CV score: 0.8345135476152284
Generation 5 - Current best internal CV score: 0.8362626487166356

In [11]:
print(tpot.score(X_test, y_test))
tpot.export('tpot_mnist_pipeline.py')

0.822